# Generated by Django 3.0.6 on 2021-04-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_footerupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerupload',
            name='about_us',
            field=models.CharField(max_length=2000),
        ),
    ]
