# Generated by Django 3.0.6 on 2021-05-05 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210428_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerupload',
            name='about_us',
            field=models.TextField(),
        ),
    ]
