# Generated by Django 3.0.6 on 2021-05-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_offer_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='photo',
            field=models.ImageField(default=None, upload_to='myimage'),
        ),
    ]
